#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x99E82A75642AC823 (scalasbt@gmail.com)
#
Name     : mvn-compiler-interface
Version  : 0.13.15
Release  : 2
URL      : https://piccolo.link/sbt-0.13.15.tgz
Source0  : https://piccolo.link/sbt-0.13.15.tgz
Source1  : https://repo.maven.apache.org/maven2/com/typesafe/sbt/compiler-interface/0.13.15/compiler-interface-0.13.15-sources.jar
Source2  : https://repo1.maven.org/maven2/com/typesafe/sbt/compiler-interface/0.13.15/compiler-interface-0.13.15.pom
Source99 : https://piccolo.link/sbt-0.13.15.tgz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mvn-compiler-interface-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-compiler-interface package.
Group: Data

%description data
data components for the mvn-compiler-interface package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/typesafe/sbt/compiler-interface/0.13.15
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/typesafe/sbt/compiler-interface/0.13.15/compiler-interface-0.13.15-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/typesafe/sbt/compiler-interface/0.13.15
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/typesafe/sbt/compiler-interface/0.13.15/compiler-interface-0.13.15.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/typesafe/sbt/compiler-interface/0.13.15/compiler-interface-0.13.15-sources.jar
/usr/share/java/.m2/repository/com/typesafe/sbt/compiler-interface/0.13.15/compiler-interface-0.13.15.pom
